#ifndef IKT203_COURSE_ASSIGNMENTS_GENERATEEMPLOYEEID_H
#define IKT203_COURSE_ASSIGNMENTS_GENERATEEMPLOYEEID_H

#pragma once

int GenerateEmployeeID();

#endif //IKT203_COURSE_ASSIGNMENTS_GENERATEEMPLOYEEID_H